#!/bin/bash

# ====================
# CONFIGURATION
# ====================
# shellcheck source=home/steam/zombob/config.cfg
CONFIGURATION_PATH="$HOME/zombob/config.cfg"
source "$CONFIGURATION_PATH"

# ====================
# HELPERS
# ====================
for HLP_PATH in $ZOMBOB_HELPERS_PATH
do
  source "$HLP_PATH"
done

# ====================
# COMMANDS
# ====================
for CMD_PATH in $ZOMBOB_COMMANDS_PATH
do
  source "$CMD_PATH"
done

# ====================
# INPUT PARSER
# ====================
if [ "$#" == 0 ]
  then
    showHelp
    exit
fi

while getopts s:c:i: flag
do
  case "${flag}" in
    s) CUSTOM_SERVER_NAME=${OPTARG}
      updateConfig
      source "$CONFIGURATION_PATH"
      ;;
    c) TYPE=${OPTARG};;
    i) ARG=${OPTARG};;
    *) showHelp
      ;;
  esac
done

# ====================
# MAIN INPUT HANDLER
# ====================
# shellcheck disable=SC2120
actionSelector() {

  COMMAND=$TYPE
  INPUT=$ARG
  if [ -n "$1" ]
  then
    COMMAND=$1
  fi
  if [ -n "$2" ]
  then
    INPUT=$2
  fi

  createDataFolder

  case "$COMMAND" in
    "status")
      status ;;
    "start")
      start ;;
    "stop")
      stop "$INPUT" "test" ;;
    "restart")
      restart "$INPUT" ;;
    "reset")
      reset ;;
    "update")
      update ;;
    "create-backup")
      createBackup ;;
    "clean-backups")
      cleanBackups ;;
    "check-update-mods")
      checkUpdateMods ;;
    "force-update-mods")
      forceUpdateMods ;;
    "send-message")
      sendMessage "$INPUT" ;;
    "count-players")
      countPlayers "$INPUT" ;;
    "load-crontab")
      loadCrontabBackup ;;
    "exit")
      echo "Goodbye!"
      exit 0;;
    *)
      echo "Unknown action. Input -h to see all options"
  esac
}

actionSelector


